name: Update bots

# Controls when the workflow will run
on:
  schedule:
    - cron: '0 0,8,12,16,20 * * *'
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  pull-and-commit:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          if ! command -v git &>/dev/null && ! command -v wget &>/dev/null && ! command -v npm &>/dev/null; then sudo apt install git wget npm; fi
          git config --global user.name Crilum
          git config --global user.email 91354257+Crilum@users.noreply.github.com
          git config --global pull.ff only
          rm -rf ./compliments/ ./TGN-bot/
          git clone https://github.com/Crilum/compliments/
          cd ./compliments/
          npm install
          cd ..
          git clone https://github.com/Crilum/TGN-bot/
          cd ./TGN-bot/
          PUPPETEER_CACHE_DIR=./node-modules/puppeteer/.cache/ npm install
          cd ..
          git add -f ./compliments/* ./TGN-bot/*
          echo "Just added files: $?"
          git commit -m "Updated compliments and TGN"
          echo "Just comitted files: $?"
          git push
          echo "Just pushed files: $?"
          
